export enum SectionCode {
  DASHBOARD = 'DASHBOARD',
  WALLET = 'WALLET',
  RECHARGE = 'RECHARGE',
  WHITDRAW = 'WHITDRAW',
  RESOURCE = 'RESOURCE',
  COMMUNITY = 'COMMUNITY',
  COMMERCE = 'COMMERCE',
  FUNDATION = 'FUNDATION',
  PURCHASE_BELAND = 'PURCHASE_BELAND',
  TRANSFER = 'TRANSFER',
  PURCHASE = 'PURCHASE',
}