import { MigrationInterface, QueryRunner } from "typeorm";

export class InitSchema1756232670787 implements MigrationInterface {
    name = 'InitSchema1756232670787'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "wallets" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "address" text, "alias" text, "qr" text, "becoin_balance" numeric(14,2) NOT NULL DEFAULT '0', "locked_balance" numeric(14,2) NOT NULL DEFAULT '0', "private_key_encrypted" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "user_id" uuid NOT NULL, "withdraw_account_id" uuid, CONSTRAINT "REL_92558c08091598f7a4439586cd" UNIQUE ("user_id"), CONSTRAINT "REL_508bfd75e0fe0663ce7a281687" UNIQUE ("withdraw_account_id"), CONSTRAINT "PK_8402e5df5a30a229380e83e4f7e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "group_members" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "role" text NOT NULL DEFAULT 'MEMBER', "joined_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "group_id" uuid, "user_id" uuid, CONSTRAINT "UQ_f5939ee0ad233ad35e03f5c65c1" UNIQUE ("group_id", "user_id"), CONSTRAINT "PK_86446139b2c96bfd0f3b8638852" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "categories" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_24dbc6126a28ff948da33e97d3b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "groups-type" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_a8858edeb0912e3ee834dd8a14a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "inventory_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "quantity_available" integer NOT NULL DEFAULT '0', "offer_label" text, "promotion_expires_at" TIMESTAMP WITH TIME ZONE, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "product_id" uuid NOT NULL, CONSTRAINT "PK_cf2f451407242e132547ac19169" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "recycled_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "is_redeemed" boolean NOT NULL DEFAULT false, "redeemed_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "product_id" uuid NOT NULL, "scanned_by_user_id" uuid NOT NULL, CONSTRAINT "PK_241d97cf95383ad4d0e96ac9e62" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "products" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" text NOT NULL, "description" text, "cost" numeric(14,2) NOT NULL DEFAULT '0', "price" numeric(14,2) NOT NULL DEFAULT '0', "image_url" text, "category_id" uuid, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_0806c755e0aca124e67c0cf6d7d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "order_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "quantity" integer NOT NULL, "unit_price" numeric NOT NULL, "total_price" numeric NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "order_id" uuid NOT NULL, "product_id" uuid NOT NULL, CONSTRAINT "PK_005269d8574e6fac0493715c308" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "payment_types" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying(50) NOT NULL, "description" character varying(255) NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_50e90c338589e2ab6408af7970b" UNIQUE ("code"), CONSTRAINT "PK_4f84450f9fd8116e201d806c74b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "transaction_states" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying(50) NOT NULL, "name" character varying(100) NOT NULL, "description" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_2f23621f6418503a705b020b342" UNIQUE ("code"), CONSTRAINT "PK_8dd7f4b7e9f2f5437479f35167e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "transaction_types" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying(50) NOT NULL, "name" character varying(100) NOT NULL, "description" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_fc49dd32ae315ae66d0edab95f9" UNIQUE ("code"), CONSTRAINT "PK_2a49fe7879bf8a02812639cea61" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "transactions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "wallet_id" uuid NOT NULL, "type_id" uuid NOT NULL, "status_id" uuid NOT NULL, "amount" numeric(14,2) NOT NULL, "amount_beicon" numeric(14,2) NOT NULL, "post_balance" numeric(14,2) NOT NULL, "payphone_transactionId" text, "clientTransactionId" uuid, "related_wallet_id" uuid, "reference" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_a219afd8dd77ed80f5a862f1db9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "payments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "amount_paid" numeric NOT NULL, "transaction_hash" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "order_id" uuid NOT NULL, "payment_type_id" uuid NOT NULL, "transaction_id" uuid NOT NULL, "user_id" uuid NOT NULL, CONSTRAINT "PK_197ab7af18c93fbb0c9b28b4a59" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_addresses" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "addressLine1" character varying(150) NOT NULL, "addressLine2" character varying(150), "city" character varying(100) NOT NULL, "state" character varying(100), "country" character varying(100) NOT NULL, "postalCode" character varying(20), "latitude" numeric(10,6), "longitude" numeric(10,6), "isDefault" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_8abbeb5e3239ff7877088ffc25b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "orders" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "status" text NOT NULL DEFAULT 'PENDING', "total_amount" numeric(10,2) NOT NULL DEFAULT '0', "total_items" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "group_id" uuid, "address_id" uuid, "leader_id" uuid NOT NULL, "payment_type_id" uuid NOT NULL, "group_ip" uuid, "address_ip" uuid, "leader_ip" uuid, CONSTRAINT "PK_710e2d4957aa5878dfe94e4ac2f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."group_invitations_role_enum" AS ENUM('LEADER', 'MEMBER')`);
        await queryRunner.query(`CREATE TYPE "public"."group_invitations_status_enum" AS ENUM('PENDING', 'ACCEPTED', 'REJECTED', 'CANCELED', 'EXPIRED')`);
        await queryRunner.query(`CREATE TABLE "group_invitations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "group_id" uuid NOT NULL, "sender_id" uuid NOT NULL, "invited_user_id" uuid, "email" character varying(255), "username" character varying(255), "phone" character varying(20), "role" "public"."group_invitations_role_enum" NOT NULL DEFAULT 'MEMBER', "status" "public"."group_invitations_status_enum" NOT NULL DEFAULT 'PENDING', "expires_at" TIMESTAMP, "reminder_sent_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_f7d0b290d6079ae9353d794227d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "groups" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" text NOT NULL, "location" text, "location_url" text, "date_time" TIMESTAMP WITH TIME ZONE, "status" text NOT NULL DEFAULT 'ACTIVE', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "leader_id" uuid NOT NULL, "group_type_id" uuid, CONSTRAINT "PK_659d1483316afb28afd3a90646e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "actions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "description" text, "transaction_hash" text, "block_number" integer, "timestamp" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "user_id" uuid NOT NULL, CONSTRAINT "PK_7bfb822f56be449c0b8adbf83cf" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "prizes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" text NOT NULL, "description" text, "cost" numeric NOT NULL, "image_url" text, "stock" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_47e4c94a955b9bf019cae56ba6a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "prize_redemptions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "status" text NOT NULL, "redemption_date" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "userId" uuid, "prizeId" uuid, CONSTRAINT "PK_b177a1998f5256d47122f14004b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "coupons" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" text NOT NULL, "type" text NOT NULL, "value" numeric NOT NULL, "is_redeemed" boolean NOT NULL DEFAULT false, "redeemed_at" TIMESTAMP WITH TIME ZONE, "expires_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "redeemed_by_user_id" uuid, CONSTRAINT "UQ_e025109230e82925843f2a14c48" UNIQUE ("code"), CONSTRAINT "PK_d7ea8864a0150183770f3e9a8cb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "roles" ("role_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" text NOT NULL, "description" text, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_648e3f5447f725579d7d4ffdfb7" UNIQUE ("name"), CONSTRAINT "PK_09f4c8130b54f35925588a37b6a" PRIMARY KEY ("role_id"))`);
        await queryRunner.query(`CREATE TABLE "admins" ("admin_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "assigned_at" TIMESTAMP WITH TIME ZONE DEFAULT NOW(), "content_permission" boolean NOT NULL DEFAULT true, "user_permission" boolean NOT NULL DEFAULT true, "moderation_permission" boolean NOT NULL DEFAULT true, "finance_permission" boolean NOT NULL DEFAULT true, "analytics_permission" boolean NOT NULL DEFAULT true, "settings_permission" boolean NOT NULL DEFAULT true, "leader_management_permission" boolean NOT NULL DEFAULT true, "company_management_permission" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_2b901dd818a2a6486994d915a68" UNIQUE ("user_id"), CONSTRAINT "REL_2b901dd818a2a6486994d915a6" UNIQUE ("user_id"), CONSTRAINT "PK_88070d08be64522fc84fdefef85" PRIMARY KEY ("admin_id"))`);
        await queryRunner.query(`CREATE TABLE "organizations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(150) NOT NULL, "legal_name" character varying(150), "ruc" character varying(20), "category" character varying(100), "description" text, "phone" character varying(20), "email" character varying(100), "address" character varying(255), "city" character varying(100), "province" character varying(100), "country" character varying(100), "latitude" numeric(10,7), "longitude" numeric(10,7), "website" character varying(255), "is_active" boolean NOT NULL DEFAULT true, "user_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "REL_245468c5a2914202a3081b1494" UNIQUE ("user_id"), CONSTRAINT "PK_6b031fcd0863e3f6b44230163f9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "cart_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "cart_id" uuid NOT NULL, "product_id" uuid NOT NULL, "quantity" integer NOT NULL DEFAULT '1', "unit_price" numeric(10,2) NOT NULL, "total_price" numeric(10,2) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6fccf5ec03c172d27a28a82928b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "carts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "address_id" uuid, "group_id" uuid, "payment_type_id" uuid, "total_amount" numeric(14,2) NOT NULL DEFAULT '0', "total_items" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "group_ip" uuid, CONSTRAINT "REL_2ec1c94a977b940d85a4f498ae" UNIQUE ("user_id"), CONSTRAINT "PK_b5f695a59f5ebb50af3c8160816" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_cards" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "email" character varying(150) NOT NULL, "phoneNumber" character varying(20) NOT NULL, "documentId" character varying(50) NOT NULL, "cardBrand" character varying(50) NOT NULL, "cardHolder" character varying(100) NOT NULL, "cardType" character varying(20) NOT NULL, "lastDigits" integer NOT NULL, "cardToken" character varying(255) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_8803d810c730191425d124af1ba" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "testimonies" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "content" text NOT NULL, "rating" integer, "is_approved" boolean NOT NULL DEFAULT false, "user_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_66810cc4e65709c3bb30c5679bd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "auth0_id" text, "oauth_provider" text, "email" text NOT NULL, "username" text, "full_name" text, "profile_picture_url" text, "current_balance" numeric DEFAULT '0', "role_name" text NOT NULL DEFAULT 'USER', "address" text, "phone" numeric, "country" text, "city" text, "isblocked" boolean NOT NULL DEFAULT false, "deleted_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "password" text, "role_id" uuid NOT NULL, CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "withdraw_accounts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "owner_name" text NOT NULL, "type_id" uuid NOT NULL, "cbu" character varying, "alias" character varying, "provider" character varying, "phone" character varying, "user_id" uuid NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_1d2137046834eb1ddf764332248" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "withdraw_account_types" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying NOT NULL, "name" character varying NOT NULL, "description" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_0bdc5b2bed60285fe8f27cfbddd" UNIQUE ("code"), CONSTRAINT "PK_cbacea16f7d7d30e38b0df2f13e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "users-event-beland" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_payment_id" uuid NOT NULL, "user_sale_id" uuid NOT NULL, "isRecycled" boolean NOT NULL, "amount" numeric(14,2) NOT NULL DEFAULT '0', "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b625bd840121f365caa729efe6d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_withdraws" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "observation" text, "user_id" uuid NOT NULL, "wallet_id" uuid NOT NULL, "withdraw_account_id" uuid NOT NULL, "amount_becoin" numeric(18,2) NOT NULL, "amount_usd" numeric(18,2) NOT NULL, "status_id" uuid NOT NULL, "transaction_id" uuid NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "REL_d575dda268b2845409ba2fd028" UNIQUE ("transaction_id"), CONSTRAINT "PK_8da201d99e4387ba04f5ad04896" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "resource_types" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying NOT NULL, "name" character varying(150) NOT NULL, "description" character varying(150) NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "UQ_eb10b39c6ef1ea560687e529892" UNIQUE ("code"), CONSTRAINT "PK_d3bca389a6c56e445c7487b245e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b77f3cbff28c4729d8419842e9" ON "resource_types" ("is_active") `);
        await queryRunner.query(`CREATE TABLE "resources" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" text NOT NULL, "name" text NOT NULL, "description" text NOT NULL, "url_image" text, "becoin_value" numeric(14,2) NOT NULL DEFAULT '0', "discount" numeric(14,2) NOT NULL DEFAULT '0', "is_expired" boolean NOT NULL DEFAULT false, "limit_user" integer NOT NULL DEFAULT '1', "limit_app" integer NOT NULL DEFAULT '0', "used_acount" integer NOT NULL DEFAULT '0', "expires_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "resource_type_id" uuid NOT NULL, "user_commerce_id" uuid NOT NULL, CONSTRAINT "UQ_b7ab912cd81e4b447e43d45e382" UNIQUE ("code"), CONSTRAINT "PK_632484ab9dff41bba94f9b7c85e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_resources" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "resource_id" uuid NOT NULL, "quantity" integer NOT NULL DEFAULT '1', "quantity_redeemed" integer NOT NULL DEFAULT '0', "hash_id" text NOT NULL, "qr_code" text, "is_redeemed" boolean NOT NULL DEFAULT false, "redeemed_at" TIMESTAMP WITH TIME ZONE, "expires_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_bd2dda118573d2fbb2c8c84084d" UNIQUE ("hash_id"), CONSTRAINT "PK_9b4f73db8997f9d7210ea511237" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a6aff0f62d0af51f18d6660bd1" ON "user_resources" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_d9aa67bf8ee1cd217f73bd1518" ON "user_resources" ("resource_id") `);
        await queryRunner.query(`CREATE TABLE "recycle_prices" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "material_type" character varying(50) NOT NULL, "becoin_value" numeric(14,2) NOT NULL DEFAULT '0', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_dd5f0041c596c3b017bbb36095a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "preset_amounts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "amount" numeric(12,2) NOT NULL, "message" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "user_commerce_id" uuid NOT NULL, CONSTRAINT "PK_48ee4b0480373dbb7f2f12f0013" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "auth_verifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying(6) NOT NULL, "email" character varying NOT NULL, "username" character varying, "full_name" character varying, "profile_picture_url" character varying, "role_id" uuid, "role_name" character varying, "password_hashed" character varying NOT NULL, "address" character varying, "phone" integer, "country" character varying, "city" character varying, "is_verified" boolean NOT NULL DEFAULT false, "expires_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_bc9f12997833a0f88dcb6188fd6" UNIQUE ("email"), CONSTRAINT "PK_545bf71e486aa524e51f5ed8fad" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "amount_to_payment" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_commerce_id" uuid NOT NULL, "amount" numeric(12,2) NOT NULL, "message" character varying, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_7a308489037d794de210fb400ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "product_group_types" ("product_id" uuid NOT NULL, "group_type_id" uuid NOT NULL, CONSTRAINT "PK_c336f356fc6f14d029d77ee69ae" PRIMARY KEY ("product_id", "group_type_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0712994ea9d608f47b15ea476a" ON "product_group_types" ("product_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_0087741e5ed23a18e491a2ff0c" ON "product_group_types" ("group_type_id") `);
        await queryRunner.query(`ALTER TABLE "wallets" ADD CONSTRAINT "FK_92558c08091598f7a4439586cda" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wallets" ADD CONSTRAINT "FK_508bfd75e0fe0663ce7a2816873" FOREIGN KEY ("withdraw_account_id") REFERENCES "withdraw_accounts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "group_members" ADD CONSTRAINT "FK_2c840df5db52dc6b4a1b0b69c6e" FOREIGN KEY ("group_id") REFERENCES "groups"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "group_members" ADD CONSTRAINT "FK_20a555b299f75843aa53ff8b0ee" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_items" ADD CONSTRAINT "FK_8e17955a29e8b63bb8cec3d32c5" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "recycled_items" ADD CONSTRAINT "FK_69d4cabd205e8c98c6f42d2edb9" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "recycled_items" ADD CONSTRAINT "FK_7f2b1b844405ac9bba63334035b" FOREIGN KEY ("scanned_by_user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_9a5f6868c96e0069e699f33e124" FOREIGN KEY ("category_id") REFERENCES "categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_145532db85752b29c57d2b7b1f1" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_9263386c35b6b242540f9493b00" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD CONSTRAINT "FK_0b171330be0cb621f8d73b87a9e" FOREIGN KEY ("wallet_id") REFERENCES "wallets"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD CONSTRAINT "FK_bf1cb034a93b703e528b926a75d" FOREIGN KEY ("type_id") REFERENCES "transaction_types"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD CONSTRAINT "FK_819b9b741319d533ea9e5617eb0" FOREIGN KEY ("status_id") REFERENCES "transaction_states"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_b2f7b823a21562eeca20e72b006" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_650ff857451d1502709df53d485" FOREIGN KEY ("payment_type_id") REFERENCES "payment_types"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_3c324ca49dabde7ffc0ef64675d" FOREIGN KEY ("transaction_id") REFERENCES "transactions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_427785468fb7d2733f59e7d7d39" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_addresses" ADD CONSTRAINT "FK_7a5100ce0548ef27a6f1533a5ce" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_f6828c894e0e6c5733452cfc5f2" FOREIGN KEY ("group_ip") REFERENCES "groups"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_6a648e7450e6be2eddfefe79c0c" FOREIGN KEY ("address_ip") REFERENCES "user_addresses"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_6a4e2e91f771d5c19e0ae10252b" FOREIGN KEY ("leader_ip") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_6420df7a9dc858a12d1c3f12416" FOREIGN KEY ("payment_type_id") REFERENCES "payment_types"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "group_invitations" ADD CONSTRAINT "FK_312f24bd763f755ac2c1604083c" FOREIGN KEY ("group_id") REFERENCES "groups"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "group_invitations" ADD CONSTRAINT "FK_09469e06263817c50400239c104" FOREIGN KEY ("sender_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "group_invitations" ADD CONSTRAINT "FK_704e91e3040e6f3752baf5b752e" FOREIGN KEY ("invited_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "groups" ADD CONSTRAINT "FK_fdb67d577cb1623e0d11a3fa6b0" FOREIGN KEY ("leader_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "groups" ADD CONSTRAINT "FK_34b386eb71b007000f05a110b49" FOREIGN KEY ("group_type_id") REFERENCES "groups-type"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "actions" ADD CONSTRAINT "FK_314aaf9c37b61b0a1267c1f4b59" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "prize_redemptions" ADD CONSTRAINT "FK_7c40bfd9517df0aa875026703b5" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "prize_redemptions" ADD CONSTRAINT "FK_7704b2cd9e65abdea8def84e12a" FOREIGN KEY ("prizeId") REFERENCES "prizes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "coupons" ADD CONSTRAINT "FK_2326117d6ad81572d73c73fcb17" FOREIGN KEY ("redeemed_by_user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "admins" ADD CONSTRAINT "FK_2b901dd818a2a6486994d915a68" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "organizations" ADD CONSTRAINT "FK_245468c5a2914202a3081b1494e" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cart_items" ADD CONSTRAINT "FK_6385a745d9e12a89b859bb25623" FOREIGN KEY ("cart_id") REFERENCES "carts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cart_items" ADD CONSTRAINT "FK_30e89257a105eab7648a35c7fce" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "carts" ADD CONSTRAINT "FK_2ec1c94a977b940d85a4f498aea" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "carts" ADD CONSTRAINT "FK_64d39f6b86964e5ce06f9fecf50" FOREIGN KEY ("address_id") REFERENCES "user_addresses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "carts" ADD CONSTRAINT "FK_664193e2d42d1b188a7b3d0b50f" FOREIGN KEY ("group_ip") REFERENCES "groups"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "carts" ADD CONSTRAINT "FK_0b3fe6feaf85c266d9c4005201a" FOREIGN KEY ("payment_type_id") REFERENCES "payment_types"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_cards" ADD CONSTRAINT "FK_fd1dbad94a6a2ccfc149c819076" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "testimonies" ADD CONSTRAINT "FK_987c4eb325a18ebeda68dc39447" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_a2cecd1a3531c0b041e29ba46e1" FOREIGN KEY ("role_id") REFERENCES "roles"("role_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "withdraw_accounts" ADD CONSTRAINT "FK_f26b8a8098f0a5cf9e1e2f99bfc" FOREIGN KEY ("type_id") REFERENCES "withdraw_account_types"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "withdraw_accounts" ADD CONSTRAINT "FK_4d2ea6fd555d92ad0f0b35139ca" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users-event-beland" ADD CONSTRAINT "FK_5e61cd19c56c18a17585f2c1054" FOREIGN KEY ("user_payment_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users-event-beland" ADD CONSTRAINT "FK_1850408e82038f7a81a93e35ab2" FOREIGN KEY ("user_sale_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_withdraws" ADD CONSTRAINT "FK_5ea86ed92bc11376a4b78ef82fc" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_withdraws" ADD CONSTRAINT "FK_5aadcc20c5011a270d9f185eab0" FOREIGN KEY ("wallet_id") REFERENCES "wallets"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_withdraws" ADD CONSTRAINT "FK_dd725d6c195c7718ff58df02a36" FOREIGN KEY ("withdraw_account_id") REFERENCES "withdraw_accounts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_withdraws" ADD CONSTRAINT "FK_da9fa0e08f277a32757e6103850" FOREIGN KEY ("status_id") REFERENCES "transaction_states"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_withdraws" ADD CONSTRAINT "FK_d575dda268b2845409ba2fd0289" FOREIGN KEY ("transaction_id") REFERENCES "transactions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "resources" ADD CONSTRAINT "FK_609437a6806647507a863bf2166" FOREIGN KEY ("resource_type_id") REFERENCES "resource_types"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "resources" ADD CONSTRAINT "FK_0cc9aa2f9903c03f430dafc41ed" FOREIGN KEY ("user_commerce_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_resources" ADD CONSTRAINT "FK_a6aff0f62d0af51f18d6660bd13" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_resources" ADD CONSTRAINT "FK_d9aa67bf8ee1cd217f73bd15183" FOREIGN KEY ("resource_id") REFERENCES "resources"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "preset_amounts" ADD CONSTRAINT "FK_d4317174e0acaeb7860aad8e8d6" FOREIGN KEY ("user_commerce_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "auth_verifications" ADD CONSTRAINT "FK_097d56b6740689c789b83e73b9d" FOREIGN KEY ("role_id") REFERENCES "roles"("role_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "amount_to_payment" ADD CONSTRAINT "FK_17fe41504e35ede7a1c52cfae09" FOREIGN KEY ("user_commerce_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_group_types" ADD CONSTRAINT "FK_0712994ea9d608f47b15ea476ab" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "product_group_types" ADD CONSTRAINT "FK_0087741e5ed23a18e491a2ff0cd" FOREIGN KEY ("group_type_id") REFERENCES "groups-type"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "product_group_types" DROP CONSTRAINT "FK_0087741e5ed23a18e491a2ff0cd"`);
        await queryRunner.query(`ALTER TABLE "product_group_types" DROP CONSTRAINT "FK_0712994ea9d608f47b15ea476ab"`);
        await queryRunner.query(`ALTER TABLE "amount_to_payment" DROP CONSTRAINT "FK_17fe41504e35ede7a1c52cfae09"`);
        await queryRunner.query(`ALTER TABLE "auth_verifications" DROP CONSTRAINT "FK_097d56b6740689c789b83e73b9d"`);
        await queryRunner.query(`ALTER TABLE "preset_amounts" DROP CONSTRAINT "FK_d4317174e0acaeb7860aad8e8d6"`);
        await queryRunner.query(`ALTER TABLE "user_resources" DROP CONSTRAINT "FK_d9aa67bf8ee1cd217f73bd15183"`);
        await queryRunner.query(`ALTER TABLE "user_resources" DROP CONSTRAINT "FK_a6aff0f62d0af51f18d6660bd13"`);
        await queryRunner.query(`ALTER TABLE "resources" DROP CONSTRAINT "FK_0cc9aa2f9903c03f430dafc41ed"`);
        await queryRunner.query(`ALTER TABLE "resources" DROP CONSTRAINT "FK_609437a6806647507a863bf2166"`);
        await queryRunner.query(`ALTER TABLE "user_withdraws" DROP CONSTRAINT "FK_d575dda268b2845409ba2fd0289"`);
        await queryRunner.query(`ALTER TABLE "user_withdraws" DROP CONSTRAINT "FK_da9fa0e08f277a32757e6103850"`);
        await queryRunner.query(`ALTER TABLE "user_withdraws" DROP CONSTRAINT "FK_dd725d6c195c7718ff58df02a36"`);
        await queryRunner.query(`ALTER TABLE "user_withdraws" DROP CONSTRAINT "FK_5aadcc20c5011a270d9f185eab0"`);
        await queryRunner.query(`ALTER TABLE "user_withdraws" DROP CONSTRAINT "FK_5ea86ed92bc11376a4b78ef82fc"`);
        await queryRunner.query(`ALTER TABLE "users-event-beland" DROP CONSTRAINT "FK_1850408e82038f7a81a93e35ab2"`);
        await queryRunner.query(`ALTER TABLE "users-event-beland" DROP CONSTRAINT "FK_5e61cd19c56c18a17585f2c1054"`);
        await queryRunner.query(`ALTER TABLE "withdraw_accounts" DROP CONSTRAINT "FK_4d2ea6fd555d92ad0f0b35139ca"`);
        await queryRunner.query(`ALTER TABLE "withdraw_accounts" DROP CONSTRAINT "FK_f26b8a8098f0a5cf9e1e2f99bfc"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_a2cecd1a3531c0b041e29ba46e1"`);
        await queryRunner.query(`ALTER TABLE "testimonies" DROP CONSTRAINT "FK_987c4eb325a18ebeda68dc39447"`);
        await queryRunner.query(`ALTER TABLE "user_cards" DROP CONSTRAINT "FK_fd1dbad94a6a2ccfc149c819076"`);
        await queryRunner.query(`ALTER TABLE "carts" DROP CONSTRAINT "FK_0b3fe6feaf85c266d9c4005201a"`);
        await queryRunner.query(`ALTER TABLE "carts" DROP CONSTRAINT "FK_664193e2d42d1b188a7b3d0b50f"`);
        await queryRunner.query(`ALTER TABLE "carts" DROP CONSTRAINT "FK_64d39f6b86964e5ce06f9fecf50"`);
        await queryRunner.query(`ALTER TABLE "carts" DROP CONSTRAINT "FK_2ec1c94a977b940d85a4f498aea"`);
        await queryRunner.query(`ALTER TABLE "cart_items" DROP CONSTRAINT "FK_30e89257a105eab7648a35c7fce"`);
        await queryRunner.query(`ALTER TABLE "cart_items" DROP CONSTRAINT "FK_6385a745d9e12a89b859bb25623"`);
        await queryRunner.query(`ALTER TABLE "organizations" DROP CONSTRAINT "FK_245468c5a2914202a3081b1494e"`);
        await queryRunner.query(`ALTER TABLE "admins" DROP CONSTRAINT "FK_2b901dd818a2a6486994d915a68"`);
        await queryRunner.query(`ALTER TABLE "coupons" DROP CONSTRAINT "FK_2326117d6ad81572d73c73fcb17"`);
        await queryRunner.query(`ALTER TABLE "prize_redemptions" DROP CONSTRAINT "FK_7704b2cd9e65abdea8def84e12a"`);
        await queryRunner.query(`ALTER TABLE "prize_redemptions" DROP CONSTRAINT "FK_7c40bfd9517df0aa875026703b5"`);
        await queryRunner.query(`ALTER TABLE "actions" DROP CONSTRAINT "FK_314aaf9c37b61b0a1267c1f4b59"`);
        await queryRunner.query(`ALTER TABLE "groups" DROP CONSTRAINT "FK_34b386eb71b007000f05a110b49"`);
        await queryRunner.query(`ALTER TABLE "groups" DROP CONSTRAINT "FK_fdb67d577cb1623e0d11a3fa6b0"`);
        await queryRunner.query(`ALTER TABLE "group_invitations" DROP CONSTRAINT "FK_704e91e3040e6f3752baf5b752e"`);
        await queryRunner.query(`ALTER TABLE "group_invitations" DROP CONSTRAINT "FK_09469e06263817c50400239c104"`);
        await queryRunner.query(`ALTER TABLE "group_invitations" DROP CONSTRAINT "FK_312f24bd763f755ac2c1604083c"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_6420df7a9dc858a12d1c3f12416"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_6a4e2e91f771d5c19e0ae10252b"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_6a648e7450e6be2eddfefe79c0c"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_f6828c894e0e6c5733452cfc5f2"`);
        await queryRunner.query(`ALTER TABLE "user_addresses" DROP CONSTRAINT "FK_7a5100ce0548ef27a6f1533a5ce"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_427785468fb7d2733f59e7d7d39"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_3c324ca49dabde7ffc0ef64675d"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_650ff857451d1502709df53d485"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_b2f7b823a21562eeca20e72b006"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP CONSTRAINT "FK_819b9b741319d533ea9e5617eb0"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP CONSTRAINT "FK_bf1cb034a93b703e528b926a75d"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP CONSTRAINT "FK_0b171330be0cb621f8d73b87a9e"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_9263386c35b6b242540f9493b00"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_145532db85752b29c57d2b7b1f1"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_9a5f6868c96e0069e699f33e124"`);
        await queryRunner.query(`ALTER TABLE "recycled_items" DROP CONSTRAINT "FK_7f2b1b844405ac9bba63334035b"`);
        await queryRunner.query(`ALTER TABLE "recycled_items" DROP CONSTRAINT "FK_69d4cabd205e8c98c6f42d2edb9"`);
        await queryRunner.query(`ALTER TABLE "inventory_items" DROP CONSTRAINT "FK_8e17955a29e8b63bb8cec3d32c5"`);
        await queryRunner.query(`ALTER TABLE "group_members" DROP CONSTRAINT "FK_20a555b299f75843aa53ff8b0ee"`);
        await queryRunner.query(`ALTER TABLE "group_members" DROP CONSTRAINT "FK_2c840df5db52dc6b4a1b0b69c6e"`);
        await queryRunner.query(`ALTER TABLE "wallets" DROP CONSTRAINT "FK_508bfd75e0fe0663ce7a2816873"`);
        await queryRunner.query(`ALTER TABLE "wallets" DROP CONSTRAINT "FK_92558c08091598f7a4439586cda"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0087741e5ed23a18e491a2ff0c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0712994ea9d608f47b15ea476a"`);
        await queryRunner.query(`DROP TABLE "product_group_types"`);
        await queryRunner.query(`DROP TABLE "amount_to_payment"`);
        await queryRunner.query(`DROP TABLE "auth_verifications"`);
        await queryRunner.query(`DROP TABLE "preset_amounts"`);
        await queryRunner.query(`DROP TABLE "recycle_prices"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d9aa67bf8ee1cd217f73bd1518"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a6aff0f62d0af51f18d6660bd1"`);
        await queryRunner.query(`DROP TABLE "user_resources"`);
        await queryRunner.query(`DROP TABLE "resources"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b77f3cbff28c4729d8419842e9"`);
        await queryRunner.query(`DROP TABLE "resource_types"`);
        await queryRunner.query(`DROP TABLE "user_withdraws"`);
        await queryRunner.query(`DROP TABLE "users-event-beland"`);
        await queryRunner.query(`DROP TABLE "withdraw_account_types"`);
        await queryRunner.query(`DROP TABLE "withdraw_accounts"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TABLE "testimonies"`);
        await queryRunner.query(`DROP TABLE "user_cards"`);
        await queryRunner.query(`DROP TABLE "carts"`);
        await queryRunner.query(`DROP TABLE "cart_items"`);
        await queryRunner.query(`DROP TABLE "organizations"`);
        await queryRunner.query(`DROP TABLE "admins"`);
        await queryRunner.query(`DROP TABLE "roles"`);
        await queryRunner.query(`DROP TABLE "coupons"`);
        await queryRunner.query(`DROP TABLE "prize_redemptions"`);
        await queryRunner.query(`DROP TABLE "prizes"`);
        await queryRunner.query(`DROP TABLE "actions"`);
        await queryRunner.query(`DROP TABLE "groups"`);
        await queryRunner.query(`DROP TABLE "group_invitations"`);
        await queryRunner.query(`DROP TYPE "public"."group_invitations_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."group_invitations_role_enum"`);
        await queryRunner.query(`DROP TABLE "orders"`);
        await queryRunner.query(`DROP TABLE "user_addresses"`);
        await queryRunner.query(`DROP TABLE "payments"`);
        await queryRunner.query(`DROP TABLE "transactions"`);
        await queryRunner.query(`DROP TABLE "transaction_types"`);
        await queryRunner.query(`DROP TABLE "transaction_states"`);
        await queryRunner.query(`DROP TABLE "payment_types"`);
        await queryRunner.query(`DROP TABLE "order_items"`);
        await queryRunner.query(`DROP TABLE "products"`);
        await queryRunner.query(`DROP TABLE "recycled_items"`);
        await queryRunner.query(`DROP TABLE "inventory_items"`);
        await queryRunner.query(`DROP TABLE "groups-type"`);
        await queryRunner.query(`DROP TABLE "categories"`);
        await queryRunner.query(`DROP TABLE "group_members"`);
        await queryRunner.query(`DROP TABLE "wallets"`);
    }

}
