import { MigrationInterface, QueryRunner } from "typeorm";

export class UpdateDataBase1766783510944 implements MigrationInterface {
    name = 'UpdateDataBase1766783510944'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "groups" DROP CONSTRAINT "FK_fdb67d577cb1623e0d11a3fa6b0"`);
        await queryRunner.query(`CREATE TABLE "profiles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" character varying, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_4e9da7cade0e9edd393329bb326" UNIQUE ("name"), CONSTRAINT "PK_8e520eb4da7dc01d0e190447c8e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "users-profiles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "profile_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_efd24d88454b83120ef69bacefe" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "order_item_consumptions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "order_item_id" uuid NOT NULL, "user_id" uuid NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_863c966d9cd22632d9f989fa2be" UNIQUE ("order_item_id", "user_id"), CONSTRAINT "PK_13c2fc12404cf8af439abae4df1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "hubs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(150) NOT NULL, "legal_name" character varying(150), "ruc" character varying(20), "description" text, "phone" character varying(20), "email" character varying(100), "address_id" uuid NOT NULL, "website" character varying(255), "is_active" boolean NOT NULL DEFAULT true, "user_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "REL_1531a036c5d3522a694d869914" UNIQUE ("user_id"), CONSTRAINT "PK_44b53d1f2b4568b26ce4710b843" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "hub_products" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "hub_id" uuid NOT NULL, "product_id" uuid NOT NULL, "quantity" integer NOT NULL DEFAULT '0', "stock_min" integer NOT NULL DEFAULT '0', CONSTRAINT "UQ_b09914d8c33f9269db2a10dc482" UNIQUE ("hub_id", "product_id"), CONSTRAINT "PK_bd525ef82fdb2e5533aa314ffa0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "recyclers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "address_id" uuid NOT NULL, "national_id" character varying(20) NOT NULL, "belongs_to_association" boolean NOT NULL DEFAULT false, "association_name" character varying(150), "has_collection_center" boolean NOT NULL DEFAULT false, "has_mobility" boolean NOT NULL DEFAULT false, "mobility_description" character varying(100), "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_251108524635b59196eae5b025f" UNIQUE ("user_id"), CONSTRAINT "UQ_4b842b034742f2bd300ea2f9cfe" UNIQUE ("national_id"), CONSTRAINT "REL_251108524635b59196eae5b025" UNIQUE ("user_id"), CONSTRAINT "PK_6f048fd3c953dc562ba5308ed5a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "merchants" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(150) NOT NULL, "legal_name" character varying(150), "ruc" character varying(20), "description" text, "phone" character varying(20), "email" character varying(100), "address_id" uuid NOT NULL, "website" character varying(255), "is_active" boolean NOT NULL DEFAULT true, "user_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "REL_698f612a3134c503f711479a4e" UNIQUE ("user_id"), CONSTRAINT "PK_4fd312ef25f8e05ad47bfe7ed25" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "foundations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(150) NOT NULL, "legal_name" character varying(150), "ruc" character varying(20), "description" text, "phone" character varying(20), "email" character varying(100), "address_id" uuid NOT NULL, "website" character varying(255), "is_active" boolean NOT NULL DEFAULT true, "user_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "REL_3b40616d4db8ddf6bf74ea95df" UNIQUE ("user_id"), CONSTRAINT "PK_5ae6a07d44f1d160571e159bcce" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "vehicles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying NOT NULL, "name" character varying NOT NULL, "description" text, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_6018477317389aba7db348042ee" UNIQUE ("code"), CONSTRAINT "PK_18d8646b59304dce4af3a9e35b6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "drivers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "motivation_bio" text, "profile_tagline" text, "face_image_url" text, "vehicle_type_id" uuid NOT NULL, "vehicle_description" text, "vehicle_plate" text, "vehicle_image_url" text, "is_active" boolean NOT NULL DEFAULT true, "work_address_id" uuid, "license_number" text, "rating" double precision NOT NULL DEFAULT '0', "total_deliveries" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "REL_8e224f1b8f05ace7cfc7c76d03" UNIQUE ("user_id"), CONSTRAINT "PK_92ab3fb69e566d3eb0cae896047" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "social_networks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying(50) NOT NULL, "name" character varying(100) NOT NULL, "description" character varying(255), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_fb34f36d3a4f268397ecdb620c4" UNIQUE ("code"), CONSTRAINT "PK_973974c10fd4f3f1625c24178cc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "content_categories" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying(50) NOT NULL, "name" character varying(100) NOT NULL, "description" character varying(255), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_2eb9b4bd7719f13d55a4dea080c" UNIQUE ("code"), CONSTRAINT "PK_1e90dab7a3f22189b39b01445a6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "creators" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "category_id" uuid NOT NULL, "main_social_network_id" uuid NOT NULL, "bio" character varying(255), "main_link" character varying(255), "followers_count" integer, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "REL_864c435572b9eccb3e6d9e3fb0" UNIQUE ("user_id"), CONSTRAINT "PK_b27dd693f7df17bbfc21f00166a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "group_members" DROP COLUMN "joined_at"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "price_delivery"`);
        await queryRunner.query(`ALTER TABLE "groups" DROP COLUMN "date_time"`);
        await queryRunner.query(`ALTER TABLE "groups" DROP COLUMN "leader_id"`);
        await queryRunner.query(`ALTER TABLE "groups" DROP COLUMN "location"`);
        await queryRunner.query(`ALTER TABLE "groups" DROP COLUMN "location_url"`);
        await queryRunner.query(`ALTER TABLE "groups" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "withdraw_accounts" DROP COLUMN "owner_name"`);
        await queryRunner.query(`ALTER TABLE "withdraw_accounts" DROP COLUMN "provider"`);
        await queryRunner.query(`ALTER TABLE "withdraw_accounts" DROP COLUMN "phone"`);
        await queryRunner.query(`ALTER TABLE "group_members" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "group_members" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "total_due" numeric(14,2)`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "outstanding_amount" numeric(14,2) DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "is_fully_paid" boolean DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "delivery_cost" numeric(7,2) DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "distance_km" numeric(7,2) DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "duration_min" numeric(7,2) DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "groups" ADD "description" character varying`);
        await queryRunner.query(`ALTER TABLE "groups" ADD "latitude" numeric(10,6)`);
        await queryRunner.query(`ALTER TABLE "groups" ADD "longitude" numeric(10,6)`);
        await queryRunner.query(`ALTER TABLE "groups" ADD "user_address_id" uuid`);
        await queryRunner.query(`ALTER TABLE "groups" ADD "is_active" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "groups" ADD "is_delete" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "groups" ADD "user_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "carts" ADD "delivery_cost" numeric(7,2) DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "carts" ADD "distance_km" numeric(7,2) DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "carts" ADD "duration_min" numeric(7,2) DEFAULT '0'`);
        await queryRunner.query(`CREATE TYPE "public"."withdraw_accounts_country_enum" AS ENUM('ARGENTINA', 'COLOMBIA', 'ECUADOR')`);
        await queryRunner.query(`ALTER TABLE "withdraw_accounts" ADD "country" "public"."withdraw_accounts_country_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."withdraw_accounts_currency_enum" AS ENUM('ARS', 'USD', 'COP')`);
        await queryRunner.query(`ALTER TABLE "withdraw_accounts" ADD "currency" "public"."withdraw_accounts_currency_enum"`);
        await queryRunner.query(`ALTER TABLE "withdraw_accounts" ADD "bankCode" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "withdraw_accounts" ADD "bankName" character varying(150)`);
        await queryRunner.query(`ALTER TABLE "withdraw_accounts" ADD "accountNumber" character varying(34)`);
        await queryRunner.query(`ALTER TABLE "withdraw_accounts" ADD "holderName" character varying(150)`);
        await queryRunner.query(`ALTER TABLE "withdraw_accounts" ADD "holderDocument" character varying(30)`);
        await queryRunner.query(`CREATE TYPE "public"."withdraw_accounts_holderdocumenttype_enum" AS ENUM('DNI', 'CUIT', 'CUIL', 'CEDULA', 'RUC', 'NIT')`);
        await queryRunner.query(`ALTER TABLE "withdraw_accounts" ADD "holderDocumentType" "public"."withdraw_accounts_holderdocumenttype_enum"`);
        await queryRunner.query(`ALTER TABLE "withdraw_accounts" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "group_members" DROP CONSTRAINT "FK_20a555b299f75843aa53ff8b0ee"`);
        await queryRunner.query(`ALTER TABLE "group_members" DROP CONSTRAINT "UQ_f5939ee0ad233ad35e03f5c65c1"`);
        await queryRunner.query(`ALTER TABLE "group_members" DROP COLUMN "role"`);
        await queryRunner.query(`CREATE TYPE "public"."group_member_role_enum" AS ENUM('LEADER', 'MEMBER')`);
        await queryRunner.query(`ALTER TABLE "group_members" ADD "role" "public"."group_member_role_enum" NOT NULL DEFAULT 'MEMBER'`);
        await queryRunner.query(`ALTER TABLE "group_members" ALTER COLUMN "user_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payments" ALTER COLUMN "amount_paid" TYPE numeric(14,2)`);
        await queryRunner.query(`ALTER TABLE "payments" ALTER COLUMN "amount_paid" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "order_number" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "groups" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "groups" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "withdraw_accounts" DROP CONSTRAINT "FK_2eb3fe9d3e60558f734ab098a42"`);
        await queryRunner.query(`ALTER TABLE "withdraw_accounts" ALTER COLUMN "withdraw_account_type_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "withdraw_accounts" DROP COLUMN "cbu"`);
        await queryRunner.query(`ALTER TABLE "withdraw_accounts" ADD "cbu" character varying(22)`);
        await queryRunner.query(`ALTER TABLE "withdraw_accounts" DROP COLUMN "alias"`);
        await queryRunner.query(`ALTER TABLE "withdraw_accounts" ADD "alias" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "group_members" ADD CONSTRAINT "UQ_f5939ee0ad233ad35e03f5c65c1" UNIQUE ("group_id", "user_id")`);
        await queryRunner.query(`ALTER TABLE "cart_items" ADD CONSTRAINT "UQ_dba960dbfd8636893d3c7acb18d" UNIQUE ("cart_id", "product_id")`);
        await queryRunner.query(`ALTER TABLE "group_members" ADD CONSTRAINT "FK_20a555b299f75843aa53ff8b0ee" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "groups" ADD CONSTRAINT "FK_2cb1e3bab5c13edfb8a23400d6d" FOREIGN KEY ("user_address_id") REFERENCES "user_addresses"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "groups" ADD CONSTRAINT "FK_9f71bda715870718997ed62f64b" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users-profiles" ADD CONSTRAINT "FK_41c301e19c8ba3e98054562cae1" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users-profiles" ADD CONSTRAINT "FK_7e716825063baf60fbb6686899a" FOREIGN KEY ("profile_id") REFERENCES "profiles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "withdraw_accounts" ADD CONSTRAINT "FK_2eb3fe9d3e60558f734ab098a42" FOREIGN KEY ("withdraw_account_type_id") REFERENCES "withdraw_account_types"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_item_consumptions" ADD CONSTRAINT "FK_a5bf789bcdb1ecb237d19713920" FOREIGN KEY ("order_item_id") REFERENCES "order_items"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_item_consumptions" ADD CONSTRAINT "FK_7401a78135d1940a74fc58c52a8" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hubs" ADD CONSTRAINT "FK_71f00dcc4c32b8b4dcaad62cac4" FOREIGN KEY ("address_id") REFERENCES "user_addresses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hubs" ADD CONSTRAINT "FK_1531a036c5d3522a694d8699147" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hub_products" ADD CONSTRAINT "FK_afa01882cdd8d6c64c6d9b537b3" FOREIGN KEY ("hub_id") REFERENCES "hubs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hub_products" ADD CONSTRAINT "FK_95f0d547a761a55441046da351e" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "recyclers" ADD CONSTRAINT "FK_251108524635b59196eae5b025f" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "recyclers" ADD CONSTRAINT "FK_14a026cec062fc4e9e7330c2716" FOREIGN KEY ("address_id") REFERENCES "user_addresses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "merchants" ADD CONSTRAINT "FK_25a870d1b98cf4195f9bd1eb16e" FOREIGN KEY ("address_id") REFERENCES "user_addresses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "merchants" ADD CONSTRAINT "FK_698f612a3134c503f711479a4e5" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "foundations" ADD CONSTRAINT "FK_cd2a56bf4d0c8c7bf510533ae2f" FOREIGN KEY ("address_id") REFERENCES "user_addresses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "foundations" ADD CONSTRAINT "FK_3b40616d4db8ddf6bf74ea95dfc" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "drivers" ADD CONSTRAINT "FK_8e224f1b8f05ace7cfc7c76d03b" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "drivers" ADD CONSTRAINT "FK_79d336c62b18524975b5480dc05" FOREIGN KEY ("vehicle_type_id") REFERENCES "vehicles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "drivers" ADD CONSTRAINT "FK_722b6fdd68d28a15b2287d956a4" FOREIGN KEY ("work_address_id") REFERENCES "user_addresses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "creators" ADD CONSTRAINT "FK_864c435572b9eccb3e6d9e3fb0d" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "creators" ADD CONSTRAINT "FK_a784cbb133821c5dcd4ca19e487" FOREIGN KEY ("category_id") REFERENCES "content_categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "creators" ADD CONSTRAINT "FK_9b30e22e856f12b83605ad8c2b5" FOREIGN KEY ("main_social_network_id") REFERENCES "social_networks"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "creators" DROP CONSTRAINT "FK_9b30e22e856f12b83605ad8c2b5"`);
        await queryRunner.query(`ALTER TABLE "creators" DROP CONSTRAINT "FK_a784cbb133821c5dcd4ca19e487"`);
        await queryRunner.query(`ALTER TABLE "creators" DROP CONSTRAINT "FK_864c435572b9eccb3e6d9e3fb0d"`);
        await queryRunner.query(`ALTER TABLE "drivers" DROP CONSTRAINT "FK_722b6fdd68d28a15b2287d956a4"`);
        await queryRunner.query(`ALTER TABLE "drivers" DROP CONSTRAINT "FK_79d336c62b18524975b5480dc05"`);
        await queryRunner.query(`ALTER TABLE "drivers" DROP CONSTRAINT "FK_8e224f1b8f05ace7cfc7c76d03b"`);
        await queryRunner.query(`ALTER TABLE "foundations" DROP CONSTRAINT "FK_3b40616d4db8ddf6bf74ea95dfc"`);
        await queryRunner.query(`ALTER TABLE "foundations" DROP CONSTRAINT "FK_cd2a56bf4d0c8c7bf510533ae2f"`);
        await queryRunner.query(`ALTER TABLE "merchants" DROP CONSTRAINT "FK_698f612a3134c503f711479a4e5"`);
        await queryRunner.query(`ALTER TABLE "merchants" DROP CONSTRAINT "FK_25a870d1b98cf4195f9bd1eb16e"`);
        await queryRunner.query(`ALTER TABLE "recyclers" DROP CONSTRAINT "FK_14a026cec062fc4e9e7330c2716"`);
        await queryRunner.query(`ALTER TABLE "recyclers" DROP CONSTRAINT "FK_251108524635b59196eae5b025f"`);
        await queryRunner.query(`ALTER TABLE "hub_products" DROP CONSTRAINT "FK_95f0d547a761a55441046da351e"`);
        await queryRunner.query(`ALTER TABLE "hub_products" DROP CONSTRAINT "FK_afa01882cdd8d6c64c6d9b537b3"`);
        await queryRunner.query(`ALTER TABLE "hubs" DROP CONSTRAINT "FK_1531a036c5d3522a694d8699147"`);
        await queryRunner.query(`ALTER TABLE "hubs" DROP CONSTRAINT "FK_71f00dcc4c32b8b4dcaad62cac4"`);
        await queryRunner.query(`ALTER TABLE "order_item_consumptions" DROP CONSTRAINT "FK_7401a78135d1940a74fc58c52a8"`);
        await queryRunner.query(`ALTER TABLE "order_item_consumptions" DROP CONSTRAINT "FK_a5bf789bcdb1ecb237d19713920"`);
        await queryRunner.query(`ALTER TABLE "withdraw_accounts" DROP CONSTRAINT "FK_2eb3fe9d3e60558f734ab098a42"`);
        await queryRunner.query(`ALTER TABLE "users-profiles" DROP CONSTRAINT "FK_7e716825063baf60fbb6686899a"`);
        await queryRunner.query(`ALTER TABLE "users-profiles" DROP CONSTRAINT "FK_41c301e19c8ba3e98054562cae1"`);
        await queryRunner.query(`ALTER TABLE "groups" DROP CONSTRAINT "FK_9f71bda715870718997ed62f64b"`);
        await queryRunner.query(`ALTER TABLE "groups" DROP CONSTRAINT "FK_2cb1e3bab5c13edfb8a23400d6d"`);
        await queryRunner.query(`ALTER TABLE "group_members" DROP CONSTRAINT "FK_20a555b299f75843aa53ff8b0ee"`);
        await queryRunner.query(`ALTER TABLE "cart_items" DROP CONSTRAINT "UQ_dba960dbfd8636893d3c7acb18d"`);
        await queryRunner.query(`ALTER TABLE "group_members" DROP CONSTRAINT "UQ_f5939ee0ad233ad35e03f5c65c1"`);
        await queryRunner.query(`ALTER TABLE "withdraw_accounts" DROP COLUMN "alias"`);
        await queryRunner.query(`ALTER TABLE "withdraw_accounts" ADD "alias" character varying`);
        await queryRunner.query(`ALTER TABLE "withdraw_accounts" DROP COLUMN "cbu"`);
        await queryRunner.query(`ALTER TABLE "withdraw_accounts" ADD "cbu" character varying`);
        await queryRunner.query(`ALTER TABLE "withdraw_accounts" ALTER COLUMN "withdraw_account_type_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "withdraw_accounts" ADD CONSTRAINT "FK_2eb3fe9d3e60558f734ab098a42" FOREIGN KEY ("withdraw_account_type_id") REFERENCES "withdraw_account_types"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "groups" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "groups" ADD "name" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "order_number" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payments" ALTER COLUMN "amount_paid" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "payments" ALTER COLUMN "amount_paid" TYPE numeric`);
        await queryRunner.query(`ALTER TABLE "group_members" ALTER COLUMN "user_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "group_members" DROP COLUMN "role"`);
        await queryRunner.query(`DROP TYPE "public"."group_member_role_enum"`);
        await queryRunner.query(`ALTER TABLE "group_members" ADD "role" text NOT NULL DEFAULT 'MEMBER'`);
        await queryRunner.query(`ALTER TABLE "group_members" ADD CONSTRAINT "UQ_f5939ee0ad233ad35e03f5c65c1" UNIQUE ("group_id", "user_id")`);
        await queryRunner.query(`ALTER TABLE "group_members" ADD CONSTRAINT "FK_20a555b299f75843aa53ff8b0ee" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "withdraw_accounts" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "withdraw_accounts" DROP COLUMN "holderDocumentType"`);
        await queryRunner.query(`DROP TYPE "public"."withdraw_accounts_holderdocumenttype_enum"`);
        await queryRunner.query(`ALTER TABLE "withdraw_accounts" DROP COLUMN "holderDocument"`);
        await queryRunner.query(`ALTER TABLE "withdraw_accounts" DROP COLUMN "holderName"`);
        await queryRunner.query(`ALTER TABLE "withdraw_accounts" DROP COLUMN "accountNumber"`);
        await queryRunner.query(`ALTER TABLE "withdraw_accounts" DROP COLUMN "bankName"`);
        await queryRunner.query(`ALTER TABLE "withdraw_accounts" DROP COLUMN "bankCode"`);
        await queryRunner.query(`ALTER TABLE "withdraw_accounts" DROP COLUMN "currency"`);
        await queryRunner.query(`DROP TYPE "public"."withdraw_accounts_currency_enum"`);
        await queryRunner.query(`ALTER TABLE "withdraw_accounts" DROP COLUMN "country"`);
        await queryRunner.query(`DROP TYPE "public"."withdraw_accounts_country_enum"`);
        await queryRunner.query(`ALTER TABLE "carts" DROP COLUMN "duration_min"`);
        await queryRunner.query(`ALTER TABLE "carts" DROP COLUMN "distance_km"`);
        await queryRunner.query(`ALTER TABLE "carts" DROP COLUMN "delivery_cost"`);
        await queryRunner.query(`ALTER TABLE "groups" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "groups" DROP COLUMN "is_delete"`);
        await queryRunner.query(`ALTER TABLE "groups" DROP COLUMN "is_active"`);
        await queryRunner.query(`ALTER TABLE "groups" DROP COLUMN "user_address_id"`);
        await queryRunner.query(`ALTER TABLE "groups" DROP COLUMN "longitude"`);
        await queryRunner.query(`ALTER TABLE "groups" DROP COLUMN "latitude"`);
        await queryRunner.query(`ALTER TABLE "groups" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "duration_min"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "distance_km"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "delivery_cost"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "is_fully_paid"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "outstanding_amount"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "total_due"`);
        await queryRunner.query(`ALTER TABLE "group_members" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "group_members" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "withdraw_accounts" ADD "phone" character varying`);
        await queryRunner.query(`ALTER TABLE "withdraw_accounts" ADD "provider" character varying`);
        await queryRunner.query(`ALTER TABLE "withdraw_accounts" ADD "owner_name" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "groups" ADD "status" text NOT NULL DEFAULT 'ACTIVE'`);
        await queryRunner.query(`ALTER TABLE "groups" ADD "location_url" text`);
        await queryRunner.query(`ALTER TABLE "groups" ADD "location" text`);
        await queryRunner.query(`ALTER TABLE "groups" ADD "leader_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "groups" ADD "date_time" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "price_delivery" numeric(10,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "group_members" ADD "joined_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`DROP TABLE "creators"`);
        await queryRunner.query(`DROP TABLE "content_categories"`);
        await queryRunner.query(`DROP TABLE "social_networks"`);
        await queryRunner.query(`DROP TABLE "drivers"`);
        await queryRunner.query(`DROP TABLE "vehicles"`);
        await queryRunner.query(`DROP TABLE "foundations"`);
        await queryRunner.query(`DROP TABLE "merchants"`);
        await queryRunner.query(`DROP TABLE "recyclers"`);
        await queryRunner.query(`DROP TABLE "hub_products"`);
        await queryRunner.query(`DROP TABLE "hubs"`);
        await queryRunner.query(`DROP TABLE "order_item_consumptions"`);
        await queryRunner.query(`DROP TABLE "users-profiles"`);
        await queryRunner.query(`DROP TABLE "profiles"`);
        await queryRunner.query(`ALTER TABLE "groups" ADD CONSTRAINT "FK_fdb67d577cb1623e0d11a3fa6b0" FOREIGN KEY ("leader_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

}
