import { MigrationInterface, QueryRunner } from "typeorm";

export class UpdateDataBaseMigration1771945863333 implements MigrationInterface {
    name = 'UpdateDataBaseMigration1771945863333'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "cart_items" DROP CONSTRAINT "UQ_dba960dbfd8636893d3c7acb18d"`);
        await queryRunner.query(`CREATE TABLE "group_privacies" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying NOT NULL, "name" character varying NOT NULL, "description" character varying, "is_visible" boolean NOT NULL DEFAULT true, "allow_free_join" boolean NOT NULL DEFAULT false, "is_active" boolean NOT NULL DEFAULT true, CONSTRAINT "UQ_a808664bb78d436d85a80956b1c" UNIQUE ("code"), CONSTRAINT "PK_b35ef155e06e0b08e7834b5be4f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "services" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(150) NOT NULL, "description" character varying(500), "cost" numeric(12,2), "price" numeric(12,2), "price_becoin" numeric(12,2), "day_limit_cancelled" integer, "porcent_cancelled" integer, "image_url" character varying(500), "is_available" boolean NOT NULL DEFAULT true, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_ba2d347a3168a296416c6c5ccb2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "group_services" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "group_id" uuid NOT NULL, "service_id" uuid NOT NULL, "payment_type_id" uuid NOT NULL, "total_becoin" numeric(10,2) NOT NULL, "is_completed" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_2f2eae51edecb5dedb3a8e82ee6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "group_member_consumptions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "group_id" uuid NOT NULL, "group_member_id" uuid NOT NULL, "product_id" uuid NOT NULL, "notes" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_8fdbbb1094625a432caf132e634" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "withdraw_accounts" DROP COLUMN "bankCode"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "total_due"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "outstanding_amount"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "is_fully_paid"`);
        await queryRunner.query(`ALTER TABLE "carts" DROP COLUMN "total_weight_recycled"`);
        await queryRunner.query(`ALTER TABLE "groups" DROP COLUMN "latitude"`);
        await queryRunner.query(`ALTER TABLE "groups" DROP COLUMN "longitude"`);
        await queryRunner.query(`ALTER TABLE "wallets" ADD "becoin_orange" numeric(14,2) DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "group_members" ADD "pending_amount_group" numeric(10,2) DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "group_members" ADD "pending_amount_personal" numeric(10,2) DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "group_members" ADD "pendingAmount" numeric(10,2) DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "group_members" ADD "paied" boolean DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "groups-type" ADD "image_url" character varying`);
        await queryRunner.query(`ALTER TABLE "products" ADD "quantity" integer DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD "unit_weight" numeric(7,3) DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD "user_id" uuid`);
        await queryRunner.query(`ALTER TABLE "user_addresses" ADD "is_active" boolean DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "paied" boolean DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "returned_paied" boolean DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "returned_split" boolean`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "total_becoin_returned" numeric(10,2) DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "total_becoin_paied" numeric(10,2) DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "cancelled_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "cart_items" ADD "user_id" uuid`);
        await queryRunner.query(`ALTER TABLE "groups" ADD "image_url" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "groups" ADD "message_invitation" text`);
        await queryRunner.query(`ALTER TABLE "groups" ADD "event_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "groups" ADD "privacy_id" uuid`);
        await queryRunner.query(`ALTER TABLE "groups" ADD "payment_type_id" uuid`);
        await queryRunner.query(`ALTER TABLE "groups" ADD "event_pass_id" uuid`);
        await queryRunner.query(`ALTER TABLE "groups" ADD CONSTRAINT "UQ_1a7ed9ddd5fadcfc8dc51fe4aba" UNIQUE ("event_pass_id")`);
        await queryRunner.query(`ALTER TABLE "users" ADD "total_weight_recycled" numeric(10,3) DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "payment_accounts" ADD "email" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "payment_accounts" ADD "ruc" character varying`);
        await queryRunner.query(`ALTER TABLE "payment_accounts" ADD CONSTRAINT "UQ_0daf2413dcb9f4490344c495f35" UNIQUE ("ruc")`);
        await queryRunner.query(`ALTER TABLE "payment_accounts" ADD "nro_account" character varying`);
        await queryRunner.query(`ALTER TABLE "payment_accounts" ADD CONSTRAINT "UQ_3ddfdc3131c8c0a40f9478754d8" UNIQUE ("nro_account")`);
        await queryRunner.query(`CREATE TYPE "public"."type_account_enum" AS ENUM('AHORRO', 'CORRIENTE')`);
        await queryRunner.query(`ALTER TABLE "payment_accounts" ADD "type_account" "public"."type_account_enum"`);
        await queryRunner.query(`ALTER TABLE "recharge_transfers" ADD "ticket_image_url" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_a922b820eeef29ac1c6800e826a"`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "user_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "carts" DROP CONSTRAINT "FK_2ec1c94a977b940d85a4f498aea"`);
        await queryRunner.query(`ALTER TABLE "carts" ALTER COLUMN "user_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payment_accounts" ALTER COLUMN "bank" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payment_accounts" ALTER COLUMN "cbu" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payment_accounts" ALTER COLUMN "alias" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "recharge_transfers" DROP CONSTRAINT "UQ_2da33f84ce2f4729e785f36cf86"`);
        await queryRunner.query(`ALTER TABLE "cart_items" ADD CONSTRAINT "UQ_2b778f523f8d8d3744f5e01df41" UNIQUE ("cart_id", "product_id", "user_id")`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_bf96e1bdbc1ce2ec1f7fe66e8c2" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_a922b820eeef29ac1c6800e826a" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cart_items" ADD CONSTRAINT "FK_b7213c20c1ecdc6597abc8f1212" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "carts" ADD CONSTRAINT "FK_2ec1c94a977b940d85a4f498aea" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "groups" ADD CONSTRAINT "FK_0f20464114fe9fd73a31d3e6132" FOREIGN KEY ("privacy_id") REFERENCES "group_privacies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "groups" ADD CONSTRAINT "FK_ce358f16e62db00395cc3f5a8b5" FOREIGN KEY ("payment_type_id") REFERENCES "payment_types"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "groups" ADD CONSTRAINT "FK_1a7ed9ddd5fadcfc8dc51fe4aba" FOREIGN KEY ("event_pass_id") REFERENCES "event_pass"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "group_services" ADD CONSTRAINT "FK_c25ead9f85623ca8edff56b3c94" FOREIGN KEY ("group_id") REFERENCES "groups"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "group_services" ADD CONSTRAINT "FK_105c840601f5e74da3a6fc5d9af" FOREIGN KEY ("service_id") REFERENCES "services"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "group_services" ADD CONSTRAINT "FK_2b9e5c2afbfcf9dcc23a8786c07" FOREIGN KEY ("payment_type_id") REFERENCES "payment_types"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "group_member_consumptions" ADD CONSTRAINT "FK_4165de00d17966566034f080ece" FOREIGN KEY ("group_id") REFERENCES "groups"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "group_member_consumptions" ADD CONSTRAINT "FK_12ecc8f4d4b639cc3b923c624a1" FOREIGN KEY ("group_member_id") REFERENCES "group_members"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "group_member_consumptions" ADD CONSTRAINT "FK_e5b759f83bdb316f5c80c55e56b" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "group_member_consumptions" DROP CONSTRAINT "FK_e5b759f83bdb316f5c80c55e56b"`);
        await queryRunner.query(`ALTER TABLE "group_member_consumptions" DROP CONSTRAINT "FK_12ecc8f4d4b639cc3b923c624a1"`);
        await queryRunner.query(`ALTER TABLE "group_member_consumptions" DROP CONSTRAINT "FK_4165de00d17966566034f080ece"`);
        await queryRunner.query(`ALTER TABLE "group_services" DROP CONSTRAINT "FK_2b9e5c2afbfcf9dcc23a8786c07"`);
        await queryRunner.query(`ALTER TABLE "group_services" DROP CONSTRAINT "FK_105c840601f5e74da3a6fc5d9af"`);
        await queryRunner.query(`ALTER TABLE "group_services" DROP CONSTRAINT "FK_c25ead9f85623ca8edff56b3c94"`);
        await queryRunner.query(`ALTER TABLE "groups" DROP CONSTRAINT "FK_1a7ed9ddd5fadcfc8dc51fe4aba"`);
        await queryRunner.query(`ALTER TABLE "groups" DROP CONSTRAINT "FK_ce358f16e62db00395cc3f5a8b5"`);
        await queryRunner.query(`ALTER TABLE "groups" DROP CONSTRAINT "FK_0f20464114fe9fd73a31d3e6132"`);
        await queryRunner.query(`ALTER TABLE "carts" DROP CONSTRAINT "FK_2ec1c94a977b940d85a4f498aea"`);
        await queryRunner.query(`ALTER TABLE "cart_items" DROP CONSTRAINT "FK_b7213c20c1ecdc6597abc8f1212"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_a922b820eeef29ac1c6800e826a"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_bf96e1bdbc1ce2ec1f7fe66e8c2"`);
        await queryRunner.query(`ALTER TABLE "cart_items" DROP CONSTRAINT "UQ_2b778f523f8d8d3744f5e01df41"`);
        await queryRunner.query(`ALTER TABLE "recharge_transfers" ADD CONSTRAINT "UQ_2da33f84ce2f4729e785f36cf86" UNIQUE ("transfer_id")`);
        await queryRunner.query(`ALTER TABLE "payment_accounts" ALTER COLUMN "alias" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payment_accounts" ALTER COLUMN "cbu" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payment_accounts" ALTER COLUMN "bank" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "carts" ALTER COLUMN "user_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "carts" ADD CONSTRAINT "FK_2ec1c94a977b940d85a4f498aea" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "user_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_a922b820eeef29ac1c6800e826a" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "recharge_transfers" DROP COLUMN "ticket_image_url"`);
        await queryRunner.query(`ALTER TABLE "payment_accounts" DROP COLUMN "type_account"`);
        await queryRunner.query(`DROP TYPE "public"."type_account_enum"`);
        await queryRunner.query(`ALTER TABLE "payment_accounts" DROP CONSTRAINT "UQ_3ddfdc3131c8c0a40f9478754d8"`);
        await queryRunner.query(`ALTER TABLE "payment_accounts" DROP COLUMN "nro_account"`);
        await queryRunner.query(`ALTER TABLE "payment_accounts" DROP CONSTRAINT "UQ_0daf2413dcb9f4490344c495f35"`);
        await queryRunner.query(`ALTER TABLE "payment_accounts" DROP COLUMN "ruc"`);
        await queryRunner.query(`ALTER TABLE "payment_accounts" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "total_weight_recycled"`);
        await queryRunner.query(`ALTER TABLE "groups" DROP CONSTRAINT "UQ_1a7ed9ddd5fadcfc8dc51fe4aba"`);
        await queryRunner.query(`ALTER TABLE "groups" DROP COLUMN "event_pass_id"`);
        await queryRunner.query(`ALTER TABLE "groups" DROP COLUMN "payment_type_id"`);
        await queryRunner.query(`ALTER TABLE "groups" DROP COLUMN "privacy_id"`);
        await queryRunner.query(`ALTER TABLE "groups" DROP COLUMN "event_at"`);
        await queryRunner.query(`ALTER TABLE "groups" DROP COLUMN "message_invitation"`);
        await queryRunner.query(`ALTER TABLE "groups" DROP COLUMN "image_url"`);
        await queryRunner.query(`ALTER TABLE "cart_items" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "cancelled_at"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "total_becoin_paied"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "total_becoin_returned"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "returned_split"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "returned_paied"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "paied"`);
        await queryRunner.query(`ALTER TABLE "user_addresses" DROP COLUMN "is_active"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP COLUMN "unit_weight"`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "quantity"`);
        await queryRunner.query(`ALTER TABLE "groups-type" DROP COLUMN "image_url"`);
        await queryRunner.query(`ALTER TABLE "group_members" DROP COLUMN "paied"`);
        await queryRunner.query(`ALTER TABLE "group_members" DROP COLUMN "pendingAmount"`);
        await queryRunner.query(`ALTER TABLE "group_members" DROP COLUMN "pending_amount_personal"`);
        await queryRunner.query(`ALTER TABLE "group_members" DROP COLUMN "pending_amount_group"`);
        await queryRunner.query(`ALTER TABLE "wallets" DROP COLUMN "becoin_orange"`);
        await queryRunner.query(`ALTER TABLE "groups" ADD "longitude" numeric(10,6)`);
        await queryRunner.query(`ALTER TABLE "groups" ADD "latitude" numeric(10,6)`);
        await queryRunner.query(`ALTER TABLE "carts" ADD "total_weight_recycled" numeric(7,3) DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "is_fully_paid" boolean DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "outstanding_amount" numeric(14,2) DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "total_due" numeric(14,2)`);
        await queryRunner.query(`ALTER TABLE "withdraw_accounts" ADD "bankCode" character varying(50)`);
        await queryRunner.query(`DROP TABLE "group_member_consumptions"`);
        await queryRunner.query(`DROP TABLE "group_services"`);
        await queryRunner.query(`DROP TABLE "services"`);
        await queryRunner.query(`DROP TABLE "group_privacies"`);
        await queryRunner.query(`ALTER TABLE "cart_items" ADD CONSTRAINT "UQ_dba960dbfd8636893d3c7acb18d" UNIQUE ("cart_id", "product_id")`);
    }

}
