import { MigrationInterface, QueryRunner } from "typeorm";

export class ActualizationCard1784024330867 implements MigrationInterface {
    name = 'ActualizationCard1784024330867'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "stripe_topups" DROP CONSTRAINT "FK_stripe_topups_wallet_id"`);
        await queryRunner.query(`ALTER TABLE "group_services" RENAME COLUMN "total_becoin" TO "total_amount"`);
        await queryRunner.query(`ALTER TABLE "topups" RENAME COLUMN "becoins_granted" TO "usd_granted"`);
        await queryRunner.query(`CREATE TABLE "gift_cards" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(150) NOT NULL, "description" text, "image_url" character varying(500), "amount" numeric(10,2) NOT NULL, "currency" character varying(10) NOT NULL DEFAULT 'USD', "expiration_days" integer, "sold_quantity" integer NOT NULL DEFAULT '0', "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_66a0b66755efd01b1749861b4aa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_GIFT_CARD_ACTIVE_CREATED" ON "gift_cards" ("is_active", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_GIFT_CARD_AMOUNT" ON "gift_cards" ("amount") `);
        await queryRunner.query(`CREATE INDEX "IDX_GIFT_CARD_CURRENCY" ON "gift_cards" ("currency") `);
        await queryRunner.query(`CREATE INDEX "IDX_GIFT_CARD_CREATED_AT" ON "gift_cards" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_GIFT_CARD_IS_ACTIVE" ON "gift_cards" ("is_active") `);
        await queryRunner.query(`CREATE TYPE "public"."user_gift_cards_status_enum" AS ENUM('ACTIVE', 'PARTIALLY_USED', 'REDEEMED', 'CANCELLED')`);
        await queryRunner.query(`CREATE TABLE "user_gift_cards" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "gift_card_id" uuid NOT NULL, "sender_user_id" uuid NOT NULL, "recipient_wallet_id" uuid NOT NULL, "message" text, "original_balance" numeric(10,2) NOT NULL, "current_balance" numeric(10,2) NOT NULL, "redeemed_at" TIMESTAMP, "expires_at" TIMESTAMP, "last_used_at" TIMESTAMP, "is_active" boolean NOT NULL DEFAULT true, "status" "public"."user_gift_cards_status_enum" NOT NULL DEFAULT 'ACTIVE', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_f28a89690717a5c252039c4530a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_USER_GIFT_CARD_STATUS_CREATED" ON "user_gift_cards" ("status", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_USER_GIFT_CARD_RECIPIENT_ACTIVE" ON "user_gift_cards" ("recipient_wallet_id", "is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_USER_GIFT_CARD_ACTIVE_EXPIRES" ON "user_gift_cards" ("is_active", "expires_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_USER_GIFT_CARD_RECIPIENT_STATUS" ON "user_gift_cards" ("recipient_wallet_id", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_USER_GIFT_CARD_TEMPLATE" ON "user_gift_cards" ("gift_card_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_USER_GIFT_CARD_RECIPIENT_WALLET" ON "user_gift_cards" ("recipient_wallet_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_USER_GIFT_CARD_SENDER" ON "user_gift_cards" ("sender_user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_USER_GIFT_CARD_CREATED_AT" ON "user_gift_cards" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_USER_GIFT_CARD_EXPIRES_AT" ON "user_gift_cards" ("expires_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_USER_GIFT_CARD_IS_ACTIVE" ON "user_gift_cards" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_USER_GIFT_CARD_STATUS" ON "user_gift_cards" ("status") `);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "price_becoin"`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "becoin_by_recycled"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP COLUMN "total_becoin"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP COLUMN "unit_becoin"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP COLUMN "amount_becoin"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP COLUMN "payphone_transactionId"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "subtotal_becoin"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "total_becoin_returned"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "total_becoin_paied"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "total_becoin"`);
        await queryRunner.query(`ALTER TABLE "event_pass" DROP COLUMN "total_dollar"`);
        await queryRunner.query(`ALTER TABLE "event_pass" DROP COLUMN "price_dollar"`);
        await queryRunner.query(`ALTER TABLE "cart_items" DROP COLUMN "total_becoin"`);
        await queryRunner.query(`ALTER TABLE "cart_items" DROP COLUMN "unit_becoin"`);
        await queryRunner.query(`ALTER TABLE "carts" DROP COLUMN "total_becoin"`);
        await queryRunner.query(`ALTER TABLE "user_withdraws" DROP COLUMN "amount_becoin"`);
        await queryRunner.query(`ALTER TABLE "stripe_topups" DROP COLUMN "becoins_granted"`);
        await queryRunner.query(`ALTER TABLE "services" DROP COLUMN "price_becoin"`);
        await queryRunner.query(`ALTER TABLE "wallets" ADD "usd_balance" numeric(14,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD "amount_usd" numeric(14,2)`);
        await queryRunner.query(`CREATE TYPE "public"."transactions_external_provider_enum" AS ENUM('STRIPE', 'PAYPHONE', 'TRANSFER')`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD "external_provider" "public"."transactions_external_provider_enum"`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD "external_reference_id" character varying`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "total_amount_paied" numeric(10,2) DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "total_amount_returned" numeric(10,2) DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "event_pass" ADD "price_usd" numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "event_pass" ADD "total_usd" numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "stripe_topups" ADD "recipient_wallet_id" uuid`);
        await queryRunner.query(`CREATE TYPE "public"."stripe_topups_owner_enum" AS ENUM('RECHARGE', 'GIFTCARD', 'EVENTPASS', 'ORDER_PAYMENT', 'EXPERIENCE')`);
        await queryRunner.query(`ALTER TABLE "stripe_topups" ADD "owner" "public"."stripe_topups_owner_enum"`);
        await queryRunner.query(`ALTER TABLE "stripe_topups" ADD "owner_id" uuid`);
        await queryRunner.query(`ALTER TABLE "stripe_topups" ADD "holder_name" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "stripe_topups" ADD "holder_instagram_tiktok" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "stripe_topups" ADD "holder_phone" character varying(30)`);
        await queryRunner.query(`ALTER TABLE "stripe_topups" ADD "holder_email" character varying(100)`);
        await queryRunner.query(`DROP INDEX "public"."wallet_alias_idx"`);
        await queryRunner.query(`ALTER TABLE "wallets" DROP COLUMN "alias"`);
        await queryRunner.query(`ALTER TABLE "wallets" ADD "alias" character varying`);
        await queryRunner.query(`CREATE INDEX "wallet_alias_idx" ON "wallets" ("alias") `);
        await queryRunner.query(`ALTER TABLE "stripe_topups" ADD CONSTRAINT "FK_451c389c12d279fa87de96c2391" FOREIGN KEY ("wallet_id") REFERENCES "wallets"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stripe_topups" ADD CONSTRAINT "FK_d4e156951f97523337fa1cf1924" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_gift_cards" ADD CONSTRAINT "FK_6a627532582100fb079eda70677" FOREIGN KEY ("gift_card_id") REFERENCES "gift_cards"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_gift_cards" ADD CONSTRAINT "FK_9c9d237183dc53f984f78ca45f6" FOREIGN KEY ("sender_user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_gift_cards" ADD CONSTRAINT "FK_0d3d07e177edaf3efa2f8d4aff4" FOREIGN KEY ("recipient_wallet_id") REFERENCES "wallets"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "user_gift_cards" DROP CONSTRAINT "FK_0d3d07e177edaf3efa2f8d4aff4"`);
        await queryRunner.query(`ALTER TABLE "user_gift_cards" DROP CONSTRAINT "FK_9c9d237183dc53f984f78ca45f6"`);
        await queryRunner.query(`ALTER TABLE "user_gift_cards" DROP CONSTRAINT "FK_6a627532582100fb079eda70677"`);
        await queryRunner.query(`ALTER TABLE "stripe_topups" DROP CONSTRAINT "FK_d4e156951f97523337fa1cf1924"`);
        await queryRunner.query(`ALTER TABLE "stripe_topups" DROP CONSTRAINT "FK_451c389c12d279fa87de96c2391"`);
        await queryRunner.query(`DROP INDEX "public"."wallet_alias_idx"`);
        await queryRunner.query(`ALTER TABLE "wallets" DROP COLUMN "alias"`);
        await queryRunner.query(`ALTER TABLE "wallets" ADD "alias" text`);
        await queryRunner.query(`CREATE INDEX "wallet_alias_idx" ON "wallets" ("alias") `);
        await queryRunner.query(`ALTER TABLE "stripe_topups" DROP COLUMN "holder_email"`);
        await queryRunner.query(`ALTER TABLE "stripe_topups" DROP COLUMN "holder_phone"`);
        await queryRunner.query(`ALTER TABLE "stripe_topups" DROP COLUMN "holder_instagram_tiktok"`);
        await queryRunner.query(`ALTER TABLE "stripe_topups" DROP COLUMN "holder_name"`);
        await queryRunner.query(`ALTER TABLE "stripe_topups" DROP COLUMN "owner_id"`);
        await queryRunner.query(`ALTER TABLE "stripe_topups" DROP COLUMN "owner"`);
        await queryRunner.query(`DROP TYPE "public"."stripe_topups_owner_enum"`);
        await queryRunner.query(`ALTER TABLE "stripe_topups" DROP COLUMN "recipient_wallet_id"`);
        await queryRunner.query(`ALTER TABLE "event_pass" DROP COLUMN "total_usd"`);
        await queryRunner.query(`ALTER TABLE "event_pass" DROP COLUMN "price_usd"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "total_amount_returned"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "total_amount_paied"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP COLUMN "external_reference_id"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP COLUMN "external_provider"`);
        await queryRunner.query(`DROP TYPE "public"."transactions_external_provider_enum"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP COLUMN "amount_usd"`);
        await queryRunner.query(`ALTER TABLE "wallets" DROP COLUMN "usd_balance"`);
        await queryRunner.query(`ALTER TABLE "services" ADD "price_becoin" numeric(12,2)`);
        await queryRunner.query(`ALTER TABLE "stripe_topups" ADD "becoins_granted" numeric(14,2)`);
        await queryRunner.query(`ALTER TABLE "user_withdraws" ADD "amount_becoin" numeric(18,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "carts" ADD "total_becoin" numeric(14,2) DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "cart_items" ADD "unit_becoin" numeric(10,2) DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "cart_items" ADD "total_becoin" numeric(10,2) DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "event_pass" ADD "price_dollar" numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "event_pass" ADD "total_dollar" numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "total_becoin" numeric(10,2) DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "total_becoin_paied" numeric(10,2) DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "total_becoin_returned" numeric(10,2) DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "subtotal_becoin" numeric(10,2) DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD "payphone_transactionId" text`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD "amount_becoin" numeric(14,2)`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD "unit_becoin" numeric(14,2)`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD "total_becoin" numeric(14,2)`);
        await queryRunner.query(`ALTER TABLE "products" ADD "becoin_by_recycled" integer DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "products" ADD "price_becoin" numeric(14,2) DEFAULT '0'`);
        await queryRunner.query(`DROP INDEX "public"."IDX_USER_GIFT_CARD_STATUS"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_USER_GIFT_CARD_IS_ACTIVE"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_USER_GIFT_CARD_EXPIRES_AT"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_USER_GIFT_CARD_CREATED_AT"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_USER_GIFT_CARD_SENDER"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_USER_GIFT_CARD_RECIPIENT_WALLET"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_USER_GIFT_CARD_TEMPLATE"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_USER_GIFT_CARD_RECIPIENT_STATUS"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_USER_GIFT_CARD_ACTIVE_EXPIRES"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_USER_GIFT_CARD_RECIPIENT_ACTIVE"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_USER_GIFT_CARD_STATUS_CREATED"`);
        await queryRunner.query(`DROP TABLE "user_gift_cards"`);
        await queryRunner.query(`DROP TYPE "public"."user_gift_cards_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_GIFT_CARD_IS_ACTIVE"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_GIFT_CARD_CREATED_AT"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_GIFT_CARD_CURRENCY"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_GIFT_CARD_AMOUNT"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_GIFT_CARD_ACTIVE_CREATED"`);
        await queryRunner.query(`DROP TABLE "gift_cards"`);
        await queryRunner.query(`ALTER TABLE "topups" RENAME COLUMN "usd_granted" TO "becoins_granted"`);
        await queryRunner.query(`ALTER TABLE "group_services" RENAME COLUMN "total_amount" TO "total_becoin"`);
        await queryRunner.query(`ALTER TABLE "stripe_topups" ADD CONSTRAINT "FK_stripe_topups_wallet_id" FOREIGN KEY ("wallet_id") REFERENCES "wallets"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
