export enum DeliveryStatusCode {
  PENDING = 'PENDING',
  PREPARING = 'PREPARING',
  ON_ROUTE = 'ON_ROUTE',
  DELIVERED = 'DELIVERED',
  RECYCLED = 'RECYCLED',
  COLLECTED = 'COLLECTED',
  CANCELLED = 'CANCELLED',
}
