export enum TransactionCode {
  RECHARGE = 'RECHARGE',
  WITHDRAW = 'WITHDRAW',
  WITHDRAW_IN = 'WITHDRAW_IN',
  TRANSFER_SEND = 'TRANSFER_SEND',
  TRANSFER_RECEIVED = 'TRANSFER_RECEIVED',
  PURCHASE = 'PURCHASE',
  PURCHASE_BELAND = 'PURCHASE_BELAND',
  SALE = 'SALE',
  SALE_BELAND = 'SALE_BELAND',
  DONATION_SEND = 'DONATION_SEND',
  DONATION_RECEIVED = 'DONATION_RECEIVED',
  RECYCLE = 'RECYCLE',
}