name: CI/CD - Deploy to AWS

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy"
        required: true
        default: "develop"
        type: choice
        options:
          - develop
          - sandbox
          - production

env:
  NODE_VERSION: 20

jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: Copy environment file
        run: |
          if [ -f "${{ github.event.inputs.environment }}.env" ]; then
            cp ${{ github.event.inputs.environment }}.env .env
          else
            echo "⚠️ No env file found for ${{ github.event.inputs.environment }}"
          fi

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Build project
        run: npm run build --quiet

      - name: Save dist as artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
          retention-days: 1

  deploy:
    name: Deploy to AWS S3
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }} # usa develop/sandbox/production
    needs: build
    env:
      ENVIRONMENT: ${{ github.event.inputs.environment }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Sync files to S3
        uses: aws-actions/s3-sync@v2
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          bucket: jetz-admin-${{ env.ENVIRONMENT }}
          source-dir: dist
          delete: true
